### ISSUE TITLE
no need for gulp to be installed globally

### ISSUE THREAD

**Issue by ghost** [unicorn-standard/starter-kit#3]
NPM is clever enough, to find gulp in projects `node_modules` folder.

Just add a gulp script into scripts section.

``` json
{
  "scripts": {
    "start": "gulp serve",
    "open": "gulp open",
    "gulp": "gulp"
  }
}
```

Now its possible to execute `npm run gulp dist` without having gulp (or anything else) installed globally. No version conflict between projects anymore. We need to remove global dendencies everywhere.

**Comment by jamesknelson** [comment]
Thanks, had no idea you could do this!
